SecuritySuite {
	MgrForcePinConstraint = %5B%7B%22type%22%3A%22minMaxLength%22%2C%22minLength%22%3A%206%2C%22maxLength%22%3A%2014%7D%5D
	MgrShowPinDlgOnExpiredPin = 1
	SetupDirectoryName = SCM_Desktop
	MgrShowAttributeChange = 0
	IsBioSupported = 0
	MgrForbidCSRExport = 1
	MgrForbidConfigChange = 1
	MgrHideStores = 1
	MgrDisableBatchCardTools = 1
	MgrShowFormatTool = 0
	MgrHideGuides = 1
	MgrHideBalloonNotification = 0
	Trace = /tmp
	MgrDisableDiagnosticTools = 1
	MgrShowAttributeGeneration = 0
	PinpadTimeout = 0
	DisablePinPad = 0
	MgrAdmin = 0
	MgrForbidTokenChangeUnblock = 0
	MgrHideChangelog = 1
	MgrForbidTokenUnblock = 1
	QSigP11PinMode = auto
	MgrForbidStoreModifs = 1
	MgrHideSystemParameter = 1
	MgrDisableSupportTools = 0
	MgrHideSignEncrypt = 1
	MgrForbidTokenModifs = 1
	MgrForbidCertificateExport = 1
	LicenseDir = /etc
	IsNxpVersion = 1
	ProfilesDir = /.local/share/SCMiddleware/Profiles
}
TokenInterfaces2 {
	IAS = libt_ias.so
}

