TokenInterfaces2 {
	IAS = libt_ias.so
}
SecuritySuite {
	MgrHideSignEncrypt = 1
	MgrHideChangelog = 1
	MgrForbidCSRExport = 1
	ProfilesDir = /.local/share/SCMiddleware/Profiles
	LicenseDir = /etc
	SetupDirectoryName = SCM_Desktop
	IsBioSupported = 0
	MgrShowPinDlgOnExpiredPin = 1
	Trace = /tmp
	QSigP11PinMode = auto
	PinpadTimeout = 0
	MgrDisableBatchCardTools = 1
	MgrHideBalloonNotification = 0
	MgrForbidTokenModifs = 1
	MgrShowAttributeGeneration = 0
	MgrForbidTokenChangeUnblock = 0
	MgrLicenseBypass = 1
	MgrForcePinConstraint = %5B%7B%22type%22%3A%22minMaxLength%22%2C%22minLength%22%3A%206%2C%22maxLength%22%3A%2014%7D%5D
	MgrShowFormatTool = 0
	DisablePinPad = 0
	MgrAdmin = 0
	MgrDisableSupportTools = 0
	MgrDisableDiagnosticTools = 1
	MgrHideGuides = 1
	MgrForbidStoreModifs = 1
	MgrHideSystemParameter = 1
	IsNxpVersion = 1
	MgrForbidCertificateExport = 1
	MgrForbidTokenUnblock = 1
	MgrForbidConfigChange = 1
	MgrHideStores = 1
	MgrShowAttributeChange = 0
}

