SecuritySuite {
	QSigP11PinMode = auto
	MgrHideStores = 1
	MgrForbidConfigChange = 1
	ProfilesDir = /.local/share/SCMiddleware/Profiles
	MgrShowFormatTool = 0
	MgrHideBalloonNotification = 0
	MgrShowPinDlgOnExpiredPin = 1
	MgrDisableDiagnosticTools = 1
	MgrForbidCSRExport = 1
	MgrForcePinConstraint = %5B%7B%22type%22%3A%22minMaxLength%22%2C%22minLength%22%3A%206%2C%22maxLength%22%3A%2014%7D%5D
	IsNxpVersion = 1
	MgrHideChangelog = 1
	LicenseDir = /etc
	MgrHideSignEncrypt = 1
	IsBioSupported = 0
	MgrHideGuides = 1
	MgrShowAttributeChange = 0
	MgrForbidCertificateExport = 1
	DisablePinPad = 0
	MgrForbidStoreModifs = 1
	MgrHideSystemParameter = 1
	Trace = /tmp
	MgrDisableSupportTools = 0
	MgrLicenseBypass = 1
	MgrAdmin = 0
	MgrForbidTokenChangeUnblock = 0
	MgrForbidTokenUnblock = 1
	PinpadTimeout = 0
	MgrShowAttributeGeneration = 0
	SetupDirectoryName = SCM_Desktop
	MgrForbidTokenModifs = 1
	MgrDisableBatchCardTools = 1
}
TokenInterfaces2 {
	IAS = libt_ias.so
}

